"""Remove first/last name & username columns from user table

Revision ID: database_v6
Revises:
Create Date: 2023-10-08 14:10:31.088339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "database_v6"
down_revision = "database_v5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "first_name")
    op.drop_column("users", "last_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.String(length=256), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(length=256), nullable=True))
