"""Add Database Tables for Agent Interaction Logging

Revision ID: database_v8
Revises:
Create Date: 2023-10-08 14:10:31.088339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "database_v8"
down_revision = "database_v7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create a table for the AgentLog class
    op.create_table(
        "agent_logs",
        sa.Column("log_id", sa.Integer(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("is_automated", sa.Boolean(), nullable=False),
        sa.Column("message", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("log_id"),
    )

    # Create a foreign key for User and AgentLog class
    op.create_foreign_key(
        op.f("fk_agent_logs_users_user_id"),
        "agent_logs",
        "users",
        ["user_id"],
        ["user_id"],
    )

    # Create a foreign key for Agent and AgentLog class
    op.create_foreign_key(
        op.f("fk_agent_logs_agents_agent_id"),
        "agent_logs",
        "agents",
        ["agent_id"],
        ["agent_id"],
    )

    # Create an index for agent_id in AgentLog class
    op.create_index(op.f("ix_agent_logs_agent_id"), "agent_logs", ["agent_id"], unique=False)

    # Create an index for user_id in AgentLog class
    op.create_index(op.f("ix_agent_logs_user_id"), "agent_logs", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the index for user_id in AgentLog class
    op.drop_index(op.f("ix_agent_logs_user_id"), table_name="agent_logs")

    # Drop the index for agent_id in AgentLog class
    op.drop_index(op.f("ix_agent_logs_agent_id"), table_name="agent_logs")

    # Drop the foreign key for Agent and AgentLog class
    op.drop_constraint(op.f("fk_agent_logs_agents_agent_id"), "agent_logs", type_="foreignkey")

    # Drop the foreign key for User and AgentLog class
    op.drop_constraint(op.f("fk_agent_logs_users_user_id"), "agent_logs", type_="foreignkey")

    # Drop the table for the AgentLog class
    op.drop_table("agent_logs")

    # ### end Alembic commands ###
