"""Initial Migration.

Revision ID: database_v1
Revises:
Create Date: 2023-10-08 14:10:31.088339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "database_v1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False, default=False),
        sa.Column("authenticated", sa.Boolean(), nullable=False, default=False),
        sa.Column("admin", sa.Boolean(), nullable=False, default=False),
        sa.Column("verified", sa.Boolean(), nullable=False, default=False),
        sa.Column("subscribed", sa.Boolean(), nullable=False, default=False),
        sa.Column("subscription_id", sa.String(length=256), nullable=True),
        sa.Column("customer_id", sa.String(length=256), nullable=True),
        sa.Column("username", sa.String(length=256), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("password", sa.String(length=256), nullable=False),
        sa.Column("first_name", sa.String(length=256), nullable=True),
        sa.Column("last_name", sa.String(length=256), nullable=True),
        sa.Column("last_message_read_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )

    op.create_table(
        "settings",
        sa.Column("setting_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("pretty_name", sa.String(length=256), nullable=True),
        sa.Column("category", sa.String(length=256), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("value", sa.String(length=256), nullable=True),
        sa.Column("data_type", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("setting_id"),
        sa.UniqueConstraint("name"),
    )

    op.create_table(
        "messages",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=True),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column("message", sa.String(length=256), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("message_id"),
    )

    op.create_foreign_key(
        op.f("fk_messages_sender_user_id"),
        "messages",
        "users",
        ["sender_id"],
        ["user_id"],
    )
    op.create_foreign_key(
        op.f("fk_messages_recipient_user_id"),
        "messages",
        "users",
        ["recipient_id"],
        ["user_id"],
    )

    op.create_index("ix_users_user_id", "users", ["user_id"], unique=False)
    op.create_index("ix_settings_setting_id", "settings", ["setting_id"], unique=False)
    op.create_index("ix_messages_message_id", "messages", ["message_id"], unique=False)
    op.create_index("ix_messages_timestamp", "messages", ["timestamp"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table("users", schema=None) as batch_op:
    #    batch_op.drop_index(batch_op.f("ix_users_user_id"))
    op.drop_index("ix_users_user_id")
    op.drop_index("ix_settings_setting_id")
    op.drop_index("ix_messages_message_id")
    op.drop_index("ix_messages_timestamp")

    op.drop_constraint("fk_messages_sender_user_id", "messages", type_="foreignkey")
    op.drop_constraint("fk_messages_recipient_user_id", "messages", type_="foreignkey")

    op.drop_table("users")
    op.drop_table("settings")
    op.drop_table("messages")
    # ### end Alembic commands ###
