"""Add Beta Users and Update Agents Table

Revision ID: database_v4
Revises:
Create Date: 2023-10-08 14:10:31.088339

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "database_v4"
down_revision = "database_v3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # -----------------------------------------------------------------
    # Beta Users
    # -----------------------------------------------------------------
    op.create_table(
        "beta_users",
        sa.Column("beta_user_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False, default=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("beta_user_id"),
    )

    op.create_index("ix_beta_users_beta_user_id", "beta_users", ["beta_user_id"], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_beta_users_beta_user_id")

    op.drop_table("beta_users")
