"""Increase size of messages column

Revision ID: database_v8
Revises:
Create Date: 2023-10-08 14:10:31.088339

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "database_v8"
down_revision = "database_v7"
branch_labels = None
depends_on = None


def upgrade():
    # commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column(
            "message",
            existing_type=sa.String(length=512),
            type_=sa.String(length=4096),
            existing_nullable=False,
        )
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column(
            "message",
            existing_type=sa.String(length=4096),
            type_=sa.String(length=512),
            existing_nullable=False,
        )
