"""Add Group Invites.

Revision ID: database_v3
Revises:
Create Date: 2023-10-08 14:10:31.088339

"""
from alembic import op
from application.common.constants import GroupInviteStates
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "database_v3"
down_revision = "database_v2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # -----------------------------------------------------------------
    # GROUP INVITES
    # -----------------------------------------------------------------
    op.create_table(
        "group_invites",
        sa.Column("group_invite_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.Integer(), nullable=False, default=GroupInviteStates.PENDING.value),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("invite_id", sa.Integer(), nullable=False),
        sa.Column("requestor_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("group_invite_id"),
    )

    op.create_foreign_key(
        op.f("fk_group_invites_groups_group_id"),
        "group_invites",
        "groups",
        ["group_id"],
        ["group_id"],
    )

    op.create_foreign_key(
        op.f("fk_group_invites_groups_invite_id"),
        "group_invites",
        "users",
        ["invite_id"],
        ["user_id"],
    )

    op.create_foreign_key(
        op.f("fk_group_invites_groups_requestor_id"),
        "group_invites",
        "users",
        ["requestor_id"],
        ["user_id"],
    )

    op.create_index(
        "ix_group_invites_group_invite_id", "group_invites", ["group_invite_id"], unique=False
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_group_invites_group_invite_id")

    op.drop_constraint("fk_group_invites_groups_group_id", "group_invites", type_="foreignkey")
    op.drop_constraint("fk_group_invites_groups_invite_id", "group_invites", type_="foreignkey")
    op.drop_constraint("fk_group_invites_groups_requestor_id", "group_invites", type_="foreignkey")

    op.drop_table("group_invites")
