"""Add User Properties & Default Properties

Revision ID: database_v5
Revises:
Create Date: 2023-10-08 14:10:31.088339

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "database_v5"
down_revision = "database_v4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "default_properties",
        sa.Column("default_property_id", sa.Integer(), nullable=False),
        sa.Column("property_name", sa.String(length=256), nullable=False),
        sa.Column("property_type", sa.String(length=256), nullable=False),
        sa.Column("property_default_value", sa.String(length=256), nullable=False),
        sa.Column("property_description", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("default_property_id"),
    )

    op.create_table(
        "properties",
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("property_value", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("default_property_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("property_id"),
    )

    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.create_foreign_key(
            op.f("fk_properties_users_user_id"),
            "users",
            ["user_id"],
            ["user_id"],
        )

        batch_op.create_foreign_key(
            op.f("fk_properties_default_properties_default_property_id"),
            "default_properties",
            ["default_property_id"],
            ["default_property_id"],
        )

    op.create_index(
        "ix_default_properties_default_property_name",
        "default_properties",
        ["property_name"],
        unique=False,
    )
    op.create_index("ix_properties_property_id", "properties", ["property_id"], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_properties_property_id")
    op.drop_index("ix_default_properties_default_property_name")

    op.drop_constraint(
        "fk_properties_default_properties_default_property_id", "properties", type_="foreignkey"
    )
    op.drop_constraint("fk_properties_users_user_id", "properties", type_="foreignkey")

    op.drop_table("properties")
    op.drop_table("default_properties")
