version: "3.9"

services:

  # NOTE - Docker Compose is STRICTLY Meant for develop purpose.

  web:
    depends_on:
      - "tasks"
      - "mariadb-service"
    image: architect:dev_test
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./application:/var/application"
    ports:
      - "3000:3000"
    environment:
      SQL_DATABASE_USER: admin
      SQL_DATABASE_PASS: REPLACEME
      SQL_DATABASE_SERVER: localhost
      SQL_DATABASE_PORT: 3306
      CELERY_BROKER: sqs://TEST:ABC123@localstack:4566

  tasks:
    depends_on:
      - "mariadb-service"
      - "localstack"
    image: architect:dev_test
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./application:/var/application"
    command: "celery -A application.wsgi_worker_compose:WORKER worker --beat -l INFO -c 2 -Q realtime,celery"
    environment:
      SQL_DATABASE_USER: admin
      SQL_DATABASE_PASS: REPLACEME
      SQL_DATABASE_SERVER: mariadb-service
      SQL_DATABASE_PORT: 3306
      CELERY_BROKER: sqs://TEST:ABC123@localstack:4566

  mariadb-service:
    image: mariadb:11
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: app
      MARIADB_USER: admin
      MARIADB_PASSWORD: REPLACEME
      MARIADB_ROOT_PASSWORD: REPLACEME  # Change Me!
    volumes:
      - mysql-data:/var/lib/mysql

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "${PORT_WEB_UI-9090}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=${DEBUG-1}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-localstack-vol}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      #- <path to startup script>:/etc/localstack/init/ready.d

  adminer:
    depends_on:
      - "mariadb-service"
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data:
  localstack-vol: