---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-environment
data:
  DEBUG: "True"
  ENV: development
  CELERY_BROKER: redis://redis-service:6379/0   # Redis Server Hostname
  CELERY_BACKEND: redis://redis-service:6379/0  # Redis Server Hostname
  MARIADB_DATABASE: app
  MARIADB_USER: admin
  MARIADB_PASSWORD: REPLACEME
  MARIADB_ROOT_PASSWORD: REPLACEME  # Change Me!
  SQL_DATABASE_USER: admin
  SQL_DATABASE_PASS: REPLACEME
  SQL_DATABASE_SERVER: mariadb-service
  SQL_DATABASE_PORT: "3306"
